### ISSUE TITLE
Wrong exit code variable

### ISSUE THREAD

**Issue by Leandros** [denysdovhan/bash-handbook#10]
The exit code of the last executed command is not saved in `#?`, but `$?`. `#?` isn't even a variable, it's a comment.

**Comment by denysdovhan** [comment]
Sorry for late! I was a little bit busy.

You're absolutely right! I'm gonna fix this as soon as possible.

**Comment by denysdovhan** [comment]
Thanks! I've fixed it in https://github.com/denysdovhan/bash-handbook/commit/f52ab6bc6488750340ab1ced09d7e4a1da327ba8.
