### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by puresoul** [denysdovhan/bash-handbook#15]
At readme. In example with shell expansion, variable now missing $. ;-)

**Comment by bucaran** [comment]
@puresoul That should be easy to patch, care to send a PR :smile:

**Comment by puresoul** [comment]
Sorry, I don't get it. What's PR?

**Comment by puresoul** [comment]
ahh, pull request :-D

**Comment by bucaran** [comment]
Thanks!

**Comment by denysdovhan** [comment]
@bucaran note: don't forget to add labels. I'd like to keep issues and pr in clean.

**Comment by bucaran** [comment]
:+1:
