### ISSUE TITLE
superflous semicolons

### ISSUE THREAD

**Issue by Leandros** [denysdovhan/bash-handbook#25]
In the `if` section many semicolons in the multiline examples are not required
Example: 

```
# Single-line
if [[ 1 -eq 1 ]]; then echo "true"; fi;

# Multi-line
if [[ 1 -eq 1 ]]; then
  echo "true"; # <- not required
fi; # <- not required
```

**Comment by denysdovhan** [comment]
Yep, it's not necessary, but I think it's a good practice, but I'll remove these semicolons to show that everyone can omit them.

Thank you for report!

**Comment by Leandros** [comment]
:+1:

**Comment by bucaran** [comment]
I agree with @Leandros! Thanks @denysdovhan
