### ISSUE TITLE
Thanks!!

### ISSUE THREAD

**Issue by sumbach** [denysdovhan/bash-handbook#26]
Thanks for creating this handbook @denysdovhan :sparkles: :+1: This is a great resource!

I have a few minor corrections and suggested improvements to propose--look for those in pull requests/issues.

Thanks again!

**Comment by denysdovhan** [comment]
Thank you for reading!

I am very pleased! I'm really glad to read feedback from users!
I've seen your pull request, but I'm tired now :tired_face:
Gonna review and merge tomorrow!

**Comment by sumbach** [comment]
No problem @denysdovhan; get some rest :sleeping:. If there's anything I can do to be helpful, please let me know.

A few of the PRs/Issues are ideas/questions rather than concrete solutions. I'm happy to collaborate if you're interested.

**Comment by bucaran** [comment]
And special thanks to all the contributors and the community who has starred the project! Closing this.

:balloon:
