### ISSUE TITLE
{folder1,folder2,folder3} doesn't work in sh

### ISSUE THREAD

**Issue by crapthings** [denysdovhan/bash-handbook#55]
thanks for this great handbook.

i have a question that is
i want to make many dirs in a folder
but what i get is just folder with a longname like this
{client,server,collections,lib,public}

    $PROJECTNAME=$1
    mkdir -p $PROJECTNAME/{client,server,collections,lib,public}

**Comment by denysdovhan** [comment]
That's OK, because of `sh` doesn't understand these [brace expansions](https://github.com/denysdovhan/bash-handbook#brace-expansion). Just run your script using **bash**:

    bash ./your_script

or add a shebang like below:

```bash
#!/usr/bin/env bash

mkdir -p "$1"/{client,server,collections,lib,public}
```

**Comment by crapthings** [comment]
awesome, what is different between these ?

    #!/bin/bash

    #!/usr/bin/env bash

**Comment by denysdovhan** [comment]
The second way is more universal. Learn more here: http://stackoverflow.com/a/16365367/5508862

**Comment by denysdovhan** [comment]
And thank you for your question! :smiley_cat:

**Comment by sumbach** [comment]
While I don't disagree with the shebang advice above, I don't think that's the cause of this problem.

The original code contains a minor typo (and common mistake): `$PROJECTNAME=$1` should be `PROJECTNAME=$1`; the `$` sigil is used when expanding variables (on the right side of the `=`) but not on the left side.

On OSX 10.10.3 with bash 3.2.57, I see the same behavior whether my shebang is `#!/bin/bash`, `#!/usr/bin/env bash`, `#!/bin/sh`, or `#!/usr/bin/env sh`.

I also confirmed that original Bourne shell (compiled from https://github.com/grml/heirloom-sh) does *not* support `{}` expansion (as @denysdovhan mentioned above).


**NOTE:** If `PROJECTNAME` could contain whitespace, take care to expand it within quotes (as @denysdovhan does with `"$1"`) to avoid undesired word-splitting.

**Comment by denysdovhan** [comment]
@sumbach hmmm, I didn't know about it. It works well for me, but maybe it's because I use Linux.

**Comment by crapthings** [comment]
okay that's my typo error, after change to 

    #!/usr/bin/env bash

it works on osx
