### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by liushuaikobe** [denysdovhan/bash-handbook#62]
I have translated this handbook(based on V2.4.0) to Chinese these days. 

It’s in [my own repo ](https://git.io/vVqrd) for now.  I plan to let others review the translation first, after that I’ll create a pull request. I myself have also read it several times and seems fine.

Thanks you for the great handbook!

**Comment by denysdovhan** [comment]
Thank you so much for translating!

Please, send a pull request as soon as it possible!

**Comment by denysdovhan** [comment]
By the way, please, add originally license to the license section. And mention that your license cover only your translation, because it seems like you are an author ;)

**Comment by liushuaikobe** [comment]
@denysdovhan  Of course I should! Thanks for the reminding. [Already did](https://github.com/liushuaikobe/bash-handbook-zh-CN#license).

I'll gather translation issues as much as possible these days, and then create a pull request.

By the way, do I need to create a `translation` directory myself to store the translations?

**Comment by denysdovhan** [comment]
> do I need to create a translation directory myself to store the translations?

Nope. I'm gonna merge #57 today or tomorrow, so you don't need to care about it.

**Comment by denysdovhan** [comment]
@liushuaikobe is everything okay?

**Comment by liushuaikobe** [comment]
@denysdovhan Yep. Everything looks good. I will create a pull request this weekend.

**Comment by denysdovhan** [comment]
@liushuaikobe great! Will wait.

**Comment by liushuaikobe** [comment]
@denysdovhan Apologize to you. My landlord drove me out  last weekend because he sold his house. So I had to find a new apartment all of those two days.

**Comment by denysdovhan** [comment]
@liushuaikobe it's OK. Will wait for you PR.

**Comment by denysdovhan** [comment]
Closed in #65.
