### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by CarlaDz** [denysdovhan/bash-handbook#63]
I'll be going through the handbook this week and [translating it](https://github.com/CarlaDz/bash-handbook) as I go.

**Comment by denysdovhan** [comment]
@CarlaDz awesome! Thank you!

Did you understand everything well? You should create a `es-ES` folder in `translations` and put your tranlation there.

P.S I have to write a small guide for contributors. Gonna do it as soon as possible.

**Comment by CarlaDz** [comment]
Yeah I did, thanks. Don't worry about it, I think it's pretty self explanatory. :)

**Comment by denysdovhan** [comment]
@CarlaDz what's up?

**Comment by CarlaDz** [comment]
Update: I should be done with it this weekend, and will ask a colleague to help me proofread it before creating the pull request.

**Comment by denysdovhan** [comment]
Okay, will wait.

**Comment by denysdovhan** [comment]
@CarlaDz hi, have you found new apartment?)

**Comment by denysdovhan** [comment]
@CarlaDz I'm gonna close this issue. If you will do translations, feel free to reopen. Thank you!
