### ISSUE TITLE
Broken link "Bash 3.2 Man page"

### ISSUE THREAD

**Issue by ujuc** [denysdovhan/bash-handbook#64]
[Bash 3.2 Man Page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/bash.1.html)

Darwin manpage is broken link.

**Comment by denysdovhan** [comment]
@ujuc that's right. It's strange, but Apple removed bash man pages. Even the first llink in Google results is broken.

**Comment by denysdovhan** [comment]
I've just removed this link. Fixed in `v2.5.1`. Thank you for reporting!
