### ISSUE TITLE
Translation Request: Spanish

### ISSUE THREAD

**Issue by edraac** [denysdovhan/bash-handbook#76]
I am able to translate this language: yes.

I have basic Bash proficiency and I'm currently using learnyoubash to practice/learn. I can volunteer to translate the bash-handbook to Spanish, what's the process to contribute translations?

**Comment by denysdovhan** [comment]
Cool!

The process is simple:

1. Fork the repo.
2. Create a new folder in `translation`. Name it as the ISO-code of your language.
3. Copy `/README.md` to the folder and translate it.
4. Commit your changes and send a PR.
5. Find someone who can check your translation. (@CarlaDc, can you help here? /cc #63)
6. Fix mistakes in translation, commit and send the changes.
7. Wait for approval from the reviewer.
8. Profit!

It's quite simple and clear. Wait for your PR!

**Comment by denysdovhan** [comment]
@edraac any updates?

**Comment by edraac** [comment]
Hi! I've been quite busy, I actually just started the translation today. I'll go along as I find time, I plan to commit changes to my fork for each translation session, you'll be able to check progress there.

**Comment by denysdovhan** [comment]
Nice. I'm looking forward for your PR.

**Comment by denysdovhan** [comment]
@edraac any updates?

I'm going to close this issue (as not actual), if you won't send me a PR for a next week.

**Comment by denysdovhan** [comment]
Feel free to reopen as soon as you will have a time and be able to translate.
