### ISSUE TITLE
Translation Request: [Arabic]

### ISSUE THREAD

**Issue by Marrakchino** [denysdovhan/bash-handbook#86]
I am able to translate this language [yes]

**Comment by denysdovhan** [comment]
@Marrakchino waiting for your PR then 😉

**Comment by Marrakchino** [comment]
Unfortunately, I think that the translation is impossible.
Github markdown doesn't support right to left languages, particularly Arabic.
I checked for any plugins/projects that support this feature but I couldn't find any. Therefore, the only solution would be to wait (I hope!) for Github to add support for right to left languages, otherwise it's impracticable.

**Comment by denysdovhan** [comment]
So sadly 😰

**Comment by denysdovhan** [comment]
I close this issue for now. Let's reopen this when RTL will be supported.
