### ISSUE TITLE
Translation Request: Japanese 

### ISSUE THREAD

**Issue by sotayamashita** [denysdovhan/bash-handbook#89]
I am able to translate this language [yes]

**Comment by sotayamashita** [comment]
I am creating a PR following this rule. https://github.com/denysdovhan/bash-handbook/issues/82#issuecomment-274785479

**Comment by denysdovhan** [comment]
Welcome @sotayamashita! Waiting for your PR 🤗

**Comment by denysdovhan** [comment]
Closing this because of no updates since April. Feel free to reopen.
