### ISSUE TITLE
Add update notifier

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/bash-handbook#9]
Add update notifier to handbook.

Concatenate message with book content.

**Comment by andrepolischuk** [comment]
You plan add a notice to start of file?

May be use this message: **!!! New version is available, run `npm install -g bash-handbook` to update !!!**

**Comment by denysdovhan** [comment]
yep, but I wanna use [update-notifier](https://www.npmjs.com/package/update-notifier).

**Comment by denysdovhan** [comment]
I'll be grateful if you send me a pull request. Of course if you can.

**Comment by andrepolischuk** [comment]
What do you think about interval for checking updates? May be 1 day?

**Comment by denysdovhan** [comment]
Sure. Do what you wanna do. I'll take a look later. If something goes
wrong, I'll fix it.
20 січ. 2016 12:56 "Andrey Polischuk" <notifications@github.com> пише:

**Comment by andrepolischuk** [comment]
Ok
